### ISSUE TITLE
[Feature] COW from bottom up

### ISSUE THREAD

**Issue by DUOLabs333** [rpodgorny/unionfs-fuse#114]
When I enable COW, is it possible for me that any copies start from the lowest read-only branch, if the file exists on multiple read-only branches?

**Comment by pongnguy** [comment]
I have a related feature request.  When I enable COW, is it possible that any copies go to the lowest write-only branch, if there are multiple higher-level RW branches?  I want separate COW write from new file writes in two different branches.  The documentation does not contradict this behavior (merely says that it is copied to a higher-level read-write branch, but does not specify what happens if there are multiple higher-level read-write branches).
