### ISSUE TITLE
The usyslog implementation does not work when not running in foreground mode.

### ISSUE THREAD

**Issue by bryder** [rpodgorny/unionfs-fuse#122]
This is tested on ubuntu 18.04, with no libfuse - not libfuse3

When you do not run unionfs in the foreground  nothing is syslogged after fuse_main() is called.

This seems to be because fuse_main returns immediately and the parent process shuts down.

Unfortunately it shuts down the thread which is supposed to consume the logs and send them to syslog.

The symptom you get is any usyslog calls done before fuse_main work fine, then nothing.

And logging works fine in debug mode because unionfs is kept in the foreground.

I fixed it by moving init_syslog() into  unionfs_init().

The only drawback I can see is that you won't be able to call usyslog before you run fuse_main.

From what I can see there is no logging before fuse_main() so at this point it's probably not a problem, and it's the logging from the running fuse that I needed to see.

I put the fix here https://github.com/bryder/unionfs-fuse/tree/test_syslogfix_with_minimal_changes for reference.

**Comment by aakefbs** [comment]
Your fix looks right and guess that issue the main reason people are not complaining that usyslog is crashing their daemon. Back in 2010ish when I created usyslog I did it in really racy way (typically with foreground  runs, I guess) and only noticed last year. I really need to find the time to fix - list splice, instead of two different locks with lock order violation...

**Comment by rpodgorny** [comment]
thanks a lot! i've hand-transplanted the fix (without the additional logging messages). this should get to the next version later today if everything goes according to plan...
