### ISSUE TITLE
unions crash

### ISSUE THREAD

**Issue by hazcod** [rpodgorny/unionfs-fuse#80]
Hello,

Running unionfs-fuse on macOS:
```
unionfs-fuse version: 2.0
(compiled with xattr support)
OSXFUSE 3.8.0
FUSE library version: 2.9.7
fuse: no mount point
```

After heavy load, the mount disappears. Any ideas how to troubleshoot?

plist daemon file:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>Label</key>
    <string>com.unionfs</string>
    <key>Program</key>
    <string>/usr/local/bin/unionfs</string>
    <key>KeepAlive</key>
    <true/>
    <key>RunAtLoad</key>
    <true/>
    <key>LaunchOnlyOnce</key>        
    <true/>
    <key>StandardOutPath</key>
    <string>/tmp/unionfs.stdout</string>
    <key>StandardErrorPath</key>
    <string>/tmp/unionfs.stderr</string>
    <key>UserName</key>
    <string>root</string>
    <key>ProgramArguments</key>
    <array>
	<string>-f</string>
	<string>-o</string>
	<string>cow,allow_other,statfs_omit_ro,atomic_o_trunc,auto_cache,big_writes,default_permissions,splice_move,splice_read</string>
	<string>-o</string>
	<string>uid=501</string>
	<string>-o</string>
	<string>gid=20</string>
	<string>/Volumes/Data/offline=RW:/Volumes/Data/online/My Drive/Media/=RO</string>
	<string>/Volumes/Data/library</string>
    </array>
  </dict>
</plist>

```

**Comment by aakefbs** [comment]
You can attach with gdb and see what happens. Although the best option
are probably these two below

1) I'm going to add some code to catch signals, so that it writes a
stack trace and core dump when something bad happens

2) I'm going compile it when sanitizer (ASAN/TSAN/MSAN), I have seen
crashes myself when I wanted to run compilations on top of it. Most
likely ASAN is going to identify what is going on.


I will do that during the next days.


Cheers,
Bernd

**Comment by rpodgorny** [comment]
this seems to be a stale issue. please try again with the current version and feel free to submit a new ticket if things are still broken. closing this one for now. thanks!

**Comment by bsbernd** [comment]
Btw, current libfuse has support to dump signals. https://github.com/libfuse/libfuse/commit/dae1184302834b52cff438fbf5322cd1c9c79c06
